apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "aitrigram.cliver-project.github.io/v1",
          "kind": "LLMEngine",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "aitrigram"
            },
            "name": "ollama-engine"
          },
          "spec": {
            "engineType": "ollama",
            "modelRefs": [
              {
                "name": "gemma3-1b"
              }
            ],
            "replicas": 1,
            "servicePort": 11434
          }
        },
        {
          "apiVersion": "aitrigram.cliver-project.github.io/v1",
          "kind": "LLMEngine",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "aitrigram"
            },
            "name": "vllm-engine"
          },
          "spec": {
            "engineType": "vllm",
            "gpu": {
              "count": 1,
              "enabled": true,
              "type": "nvidia.com/gpu"
            },
            "image": "vllm/vllm-openai:latest",
            "modelRefs": [
              {
                "name": "llama3-7b"
              }
            ],
            "port": 8000,
            "replicas": 1,
            "servicePort": 8000
          }
        },
        {
          "apiVersion": "aitrigram.cliver-project.github.io/v1",
          "kind": "ModelRepository",
          "metadata": {
            "name": "llama3-7b"
          },
          "spec": {
            "autoDownload": true,
            "source": {
              "hfTokenSecret": "huggingface-token",
              "hfTokenSecretKey": "token",
              "modelId": "meta-llama/Llama-3.2-3B-Instruct",
              "origin": "huggingface"
            },
            "storage": {
              "mountPath": "/data/models",
              "size": "50Gi",
              "storageClass": "auto"
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-04-01T13:45:50Z"
    operators.operatorframework.io/builder: operator-sdk-v1.40.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: aitrigram.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: LLMEngine
      kind: LLMEngine
      name: llmengines.aitrigram.cliver-project.github.io
      version: v1
    - description: |-
        ModelRepository is the Schema for the modelrepositories API
        ModelRepository is a cluster wide CRD so that models can be shared across namespaces.
      displayName: Model Repository
      kind: ModelRepository
      name: modelrepositories.aitrigram.cliver-project.github.io
      version: v1
  description: The operator to undle AI inference providers
  displayName: aitrigram
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - persistentvolumeclaims
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - nodes
          - pods
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - aitrigram.cliver-project.github.io
          resources:
          - llmengines
          - modelrepositories
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aitrigram.cliver-project.github.io
          resources:
          - llmengines/finalizers
          - modelrepositories/finalizers
          verbs:
          - update
        - apiGroups:
          - aitrigram.cliver-project.github.io
          resources:
          - llmengines/status
          - modelrepositories/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: aitrigram-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: aitrigram
          control-plane: controller-manager
        name: aitrigram-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: aitrigram
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: aitrigram
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - run
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: ghcr.io/cliver-project/aitrigram-controller:latest
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: aitrigram-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: aitrigram-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ai
  - agent
  - llm
  - vllm
  links:
  - name: Aitrigram
    url: https://aitrigram.domain
  maintainers:
  - email: aoingl@gmail.com
    name: lgao
  maturity: alpha
  minKubeVersion: 1.28.0
  provider:
    name: aitrigram
    url: https://github.com/cliver-project
  version: 0.0.1
