apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: modelrepository-job
    app.kubernetes.io/name: aitrigram
  name: aitrigram-modelrepository-job-runner
