apiVersion: aitrigram.cliver-project.github.io/v1
kind: LLMEngine
metadata:
  labels:
    app.kubernetes.io/name: aitrigram
    app.kubernetes.io/managed-by: kustomize
  name: ollama-engine
spec:
  engineType: ollama
  modelRefs:
    - name: gemma3-1b
  replicas: 1
  servicePort: 11434
